### ISSUE TITLE
Change domain so that more useful `configurationerror` can be raised during build

### ISSUE THREAD

**Issue by adam-a-a** [watertap-org/watertap-seto#47]
change domain so that more useful `configurationerror` can be raised during build

_Originally posted by @adam-a-a in https://github.com/watertap-org/watertap-seto/pull/41#discussion_r1162927732_

**Comment by adam-a-a** [comment]
In reference to LTMED and MEDTVC models

**Comment by Zhuoran29** [comment]
Issue resolved in PR#49.
