### ISSUE TITLE
PV_RO and LT_MED errors (with IDAES 2.0.0/ pyomo 6.6.1/ watertap 0.8.dev0)

### ISSUE THREAD

**Issue by Zhuoran29** [watertap-org/watertap-seto#53]
Tests on PV_RO and LT_MED are failing in latest PRs.
![1686149859(1)](https://github.com/watertap-org/watertap-seto/assets/43014540/708cd9f7-593f-4ec2-a75b-b1eafc1329d0)

So far it seems to trace back to the latest Pyomo package 6.6.1.

Similar issue happened to other WaterTAP models: https://github.com/watertap-org/watertap/issues/1049

**Comment by adam-a-a** [comment]
This is likely due to the latest version of Pyomo. We should try setting our verion of Pyomo to 6.5.0 in setup.py and check to see if tests pass. Then, we can create a separate PR that brings in the latest version of Pyomo and attempts to resolve these errors.

**Comment by Zhuoran29** [comment]
Resolved by installing previous Pyomo 6.5.0.
